import { useState, useRef } from "react";
import {
  FileText, Copy, Check, Sparkles, BookOpen, Clock,
  MessageSquareText, Globe, Bot, AlertTriangle, Download,
  ChevronRight, Search,
} from "lucide-react";
import { extractVideoId } from "../services/youtube";
import { fetchTranscript, TranscriptResult, formatTime } from "../services/transcript";

type Tab = "transcript" | "summary";

export default function TranscriptTool() {
  const [url, setUrl] = useState("");
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState<TranscriptResult | null>(null);
  const [copiedKey, setCopiedKey] = useState("");
  const [activeTab, setActiveTab] = useState<Tab>("transcript");
  const [searchQuery, setSearchQuery] = useState("");
  const [highlightedLine, setHighlightedLine] = useState<number | null>(null);
  const transcriptRef = useRef<HTMLDivElement>(null);

  const copy = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(""), 2000);
  };

  const handleFetch = async (videoId: string) => {
    setIsLoading(true);
    setError("");
    setResult(null);
    setSearchQuery("");
    setHighlightedLine(null);
    try {
      const data = await fetchTranscript(videoId);
      setResult(data);
      setActiveTab("transcript");
    } catch (e: any) {
      setError(e.message || "Failed to fetch transcript.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleProcess = () => {
    setError("");
    const id = extractVideoId(url);
    if (!id) { setError("Please paste a valid YouTube video link."); return; }
    handleFetch(id);
  };

  const handlePreset = (id: string) => {
    setUrl(`https://www.youtube.com/watch?v=${id}`);
    handleFetch(id);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") handleProcess();
  };

  // Filter transcript by search
  const filteredLines = result
    ? searchQuery.trim()
      ? result.lines.filter((l) =>
          l.text.toLowerCase().includes(searchQuery.toLowerCase())
        )
      : result.lines
    : [];

  // Full transcript as plain text with timestamps
  const plainTranscript = result
    ? result.lines.map((l) => `[${formatTime(l.start)}] ${l.text}`).join("\n")
    : "";

  // Summary as plain text
  const plainSummary = result
    ? [
        `Title: ${result.summary.title}`,
        `Channel: ${result.summary.channel}`,
        `Duration: ${result.summary.duration}`,
        `Words: ${result.summary.wordCount.toLocaleString()}`,
        `Language: ${result.language.toUpperCase()}`,
        `Auto-generated: ${result.isAutoGenerated ? "Yes" : "No"}`,
        "",
        "Key Points:",
        ...result.summary.keyPoints.map((p) => `• ${p}`),
        "",
        "Opening & Closing:",
        ...result.summary.topicSentences.map((s, i) => `${i === 0 ? "Opening" : "Closing"}: "${s}"`),
      ].join("\n")
    : "";

  return (
    <div className="space-y-5">
      {/* ── Input Card ── */}
      <div className="card-dark p-6">
        <div className="flex items-center gap-3 mb-5">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-500/10 border border-violet-500/20">
            <FileText className="h-5 w-5 text-violet-400" />
          </div>
          <div>
            <h3 className="text-base font-bold text-white">Transcript & Summary Generator</h3>
            <p className="text-xs text-[#8b92a9]">
              Fetches real YouTube captions — timed, searchable, and exportable. No API key needed.
            </p>
          </div>
        </div>

        <div className="flex flex-col md:flex-row gap-3">
          <input
            type="text"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="https://www.youtube.com/watch?v=..."
            className="flex-1 rounded-xl border border-[#23283a] bg-[#0d0f14] py-3 px-4 text-sm text-white placeholder-[#4f566b] focus:border-violet-500/50 focus:ring-1 focus:ring-violet-500/20 focus:outline-none transition"
          />
          <button
            disabled={isLoading}
            onClick={handleProcess}
            className="flex items-center justify-center gap-2 rounded-xl bg-violet-600 hover:bg-violet-500 disabled:opacity-50 disabled:cursor-not-allowed px-6 py-3 text-sm font-bold text-white transition shadow-lg shadow-violet-900/30 active:scale-95"
          >
            {isLoading ? (
              <div className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />
            ) : (
              <FileText className="h-4 w-4" />
            )}
            {isLoading ? "Extracting…" : "Get Transcript"}
          </button>
        </div>

        {error && (
          <div className="mt-3 flex items-start gap-2.5 rounded-xl border border-amber-500/20 bg-amber-500/5 p-3">
            <AlertTriangle className="h-4 w-4 text-amber-400 flex-shrink-0 mt-0.5" />
            <p className="text-xs text-amber-300 leading-relaxed">{error}</p>
          </div>
        )}

        <div className="mt-4 flex flex-wrap gap-2">
          <span className="text-xs text-[#4f566b] flex items-center gap-1 self-center">
            <Sparkles className="h-3 w-3 text-amber-500" /> Try a demo:
          </span>
          {[
            { id: "dQw4w9WgXcQ", label: "Rick Astley", color: "text-violet-400" },
            { id: "jNQXAC9IVRw", label: "Me at the zoo (1st YT video)", color: "text-amber-400" },
            { id: "9bZkp7q19f0", label: "Gangnam Style", color: "text-rose-400" },
          ].map(({ id, label, color }) => (
            <button
              key={id}
              onClick={() => handlePreset(id)}
              disabled={isLoading}
              className="flex items-center gap-1.5 rounded-lg border border-[#23283a] bg-[#181c25] hover:bg-[#1e2230] px-3 py-1.5 text-xs font-semibold text-[#8b92a9] hover:text-white disabled:opacity-40 transition"
            >
              <ChevronRight className={`h-3 w-3 ${color}`} /> {label}
            </button>
          ))}
        </div>
      </div>

      {/* ── Loading State ── */}
      {isLoading && (
        <div className="card-dark p-10 flex flex-col items-center gap-4">
          <div className="h-9 w-9 animate-spin rounded-full border-2 border-[#23283a] border-t-violet-500" />
          <div className="text-center">
            <p className="text-sm font-bold text-white">Fetching real captions…</p>
            <p className="text-xs text-[#8b92a9] mt-1">Connecting to YouTube via proxy · parsing caption XML</p>
          </div>
        </div>
      )}

      {/* ── Results ── */}
      {result && !isLoading && (
        <div className="space-y-4 animate-slideUp">
          {/* Stats Bar */}
          <div className="card-dark p-4">
            <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
              {[
                { icon: <MessageSquareText className="h-4 w-4 text-violet-400" />, label: "Lines", value: result.lines.length.toLocaleString() },
                { icon: <FileText className="h-4 w-4 text-blue-400" />, label: "Words", value: result.summary.wordCount.toLocaleString() },
                { icon: <Clock className="h-4 w-4 text-emerald-400" />, label: "Duration", value: result.summary.duration },
                { icon: <Globe className="h-4 w-4 text-amber-400" />, label: "Language", value: result.language.toUpperCase() },
                {
                  icon: <Bot className="h-4 w-4 text-rose-400" />,
                  label: "Type",
                  value: result.isAutoGenerated ? "Auto-generated" : "Manual",
                },
              ].map((stat) => (
                <div key={stat.label} className="flex items-center gap-2.5 rounded-xl bg-[#0d0f14] border border-[#1a1e2a] px-3 py-2.5">
                  {stat.icon}
                  <div>
                    <p className="text-[10px] text-[#4f566b] uppercase tracking-wide">{stat.label}</p>
                    <p className="text-xs font-bold text-white leading-none mt-0.5">{stat.value}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Tabs */}
          <div className="card-dark overflow-hidden">
            {/* Tab Header */}
            <div className="flex border-b border-[#1a1e2a]">
              {(["transcript", "summary"] as Tab[]).map((tab) => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`flex-1 flex items-center justify-center gap-2 py-3.5 text-xs font-bold border-b-2 transition-all capitalize ${
                    activeTab === tab
                      ? "border-violet-500 text-white bg-violet-500/5"
                      : "border-transparent text-[#4f566b] hover:text-[#8b92a9]"
                  }`}
                >
                  {tab === "transcript" ? <MessageSquareText className="h-3.5 w-3.5" /> : <BookOpen className="h-3.5 w-3.5" />}
                  {tab === "transcript" ? "Full Transcript" : "AI Summary"}
                </button>
              ))}
            </div>

            {/* Transcript Tab */}
            {activeTab === "transcript" && (
              <div className="p-5 space-y-4">
                {/* Search + Copy bar */}
                <div className="flex flex-col sm:flex-row gap-3">
                  <div className="relative flex-1">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-[#4f566b]" />
                    <input
                      type="text"
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                      placeholder="Search transcript…"
                      className="w-full pl-9 pr-4 py-2.5 rounded-xl border border-[#23283a] bg-[#0d0f14] text-sm text-white placeholder-[#4f566b] focus:border-violet-500/50 focus:outline-none transition text-xs"
                    />
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={() => copy(plainTranscript, "transcript")}
                      className="flex items-center gap-1.5 rounded-xl border border-[#23283a] bg-[#181c25] hover:bg-[#1e2230] px-4 py-2.5 text-xs font-bold text-[#8b92a9] hover:text-white transition"
                    >
                      {copiedKey === "transcript" ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
                      {copiedKey === "transcript" ? "Copied!" : "Copy"}
                    </button>
                    <a
                      href={`data:text/plain;charset=utf-8,${encodeURIComponent(plainTranscript)}`}
                      download={`transcript.txt`}
                      className="flex items-center gap-1.5 rounded-xl bg-violet-600 hover:bg-violet-500 px-4 py-2.5 text-xs font-bold text-white transition active:scale-95"
                    >
                      <Download className="h-3.5 w-3.5" /> Export .txt
                    </a>
                  </div>
                </div>

                {searchQuery && (
                  <p className="text-xs text-[#4f566b]">
                    {filteredLines.length} result{filteredLines.length !== 1 ? "s" : ""} for &ldquo;{searchQuery}&rdquo;
                  </p>
                )}

                {/* Transcript Lines */}
                <div
                  ref={transcriptRef}
                  className="h-[420px] overflow-y-auto rounded-xl border border-[#1a1e2a] bg-[#0d0f14] p-1 scrollbar-dark"
                >
                  {filteredLines.length === 0 ? (
                    <div className="flex items-center justify-center h-full text-xs text-[#4f566b]">
                      No lines match your search.
                    </div>
                  ) : (
                    filteredLines.map((line, i) => {
                      const isHighlighted = highlightedLine === i;
                      const matchesSearch =
                        searchQuery &&
                        line.text.toLowerCase().includes(searchQuery.toLowerCase());
                      return (
                        <div
                          key={i}
                          onClick={() => setHighlightedLine(isHighlighted ? null : i)}
                          className={`group flex items-start gap-3 rounded-lg px-3 py-2 cursor-pointer transition-colors ${
                            isHighlighted
                              ? "bg-violet-500/15 border border-violet-500/20"
                              : "hover:bg-[#181c25]"
                          }`}
                        >
                          <span className="flex-shrink-0 font-mono text-[10px] text-[#4f566b] pt-0.5 w-10 text-right group-hover:text-violet-400 transition-colors">
                            {formatTime(line.start)}
                          </span>
                          <span
                            className={`text-xs leading-relaxed flex-1 ${
                              isHighlighted ? "text-white" : "text-[#8b92a9] group-hover:text-white"
                            } ${matchesSearch ? "text-violet-200" : ""}`}
                          >
                            {matchesSearch ? (
                              <>
                                {line.text.split(new RegExp(`(${searchQuery})`, "gi")).map((part, pi) =>
                                  part.toLowerCase() === searchQuery.toLowerCase() ? (
                                    <mark key={pi} className="bg-violet-500/30 text-violet-200 rounded px-0.5">
                                      {part}
                                    </mark>
                                  ) : (
                                    part
                                  )
                                )}
                              </>
                            ) : (
                              line.text
                            )}
                          </span>
                        </div>
                      );
                    })
                  )}
                </div>
              </div>
            )}

            {/* Summary Tab */}
            {activeTab === "summary" && (
              <div className="p-5 space-y-5">
                <div className="flex justify-end">
                  <button
                    onClick={() => copy(plainSummary, "summary")}
                    className="flex items-center gap-1.5 rounded-xl bg-violet-600 hover:bg-violet-500 px-4 py-2.5 text-xs font-bold text-white transition active:scale-95"
                  >
                    {copiedKey === "summary" ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
                    {copiedKey === "summary" ? "Copied!" : "Copy Summary"}
                  </button>
                </div>

                {/* Video Info */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {[
                    { label: "Video Title", value: result.summary.title },
                    { label: "Channel", value: result.summary.channel },
                  ].map(({ label, value }) => (
                    <div key={label} className="rounded-xl bg-[#0d0f14] border border-[#1a1e2a] p-4">
                      <p className="text-[10px] font-bold uppercase tracking-widest text-[#4f566b] mb-1">{label}</p>
                      <p className="text-sm font-bold text-white leading-snug">{value}</p>
                    </div>
                  ))}
                </div>

                {/* Key Points */}
                <div>
                  <h4 className="text-[10px] font-bold uppercase tracking-widest text-[#4f566b] mb-3">
                    Key Points Extracted
                  </h4>
                  <div className="space-y-2">
                    {result.summary.keyPoints.map((point, i) => (
                      <div
                        key={i}
                        className="flex items-start gap-3 rounded-xl bg-[#0d0f14] border border-[#1a1e2a] p-3.5"
                      >
                        <span className="flex-shrink-0 flex h-5 w-5 items-center justify-center rounded-full bg-violet-500/15 border border-violet-500/20 text-[10px] font-extrabold text-violet-400">
                          {i + 1}
                        </span>
                        <p className="text-xs text-[#8b92a9] leading-relaxed">{point}</p>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Opening & Closing */}
                {result.summary.topicSentences.length > 0 && (
                  <div>
                    <h4 className="text-[10px] font-bold uppercase tracking-widest text-[#4f566b] mb-3">
                      Opening & Closing Lines
                    </h4>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      {result.summary.topicSentences.map((sentence, i) => (
                        <div
                          key={i}
                          className="rounded-xl border border-[#1a1e2a] bg-[#0d0f14] p-4 relative overflow-hidden"
                        >
                          <span className="absolute top-3 right-3 text-[10px] font-bold text-[#4f566b] uppercase tracking-wide">
                            {i === 0 ? "Opening" : "Closing"}
                          </span>
                          <p className="text-xs text-[#8b92a9] italic leading-relaxed mt-4">
                            &ldquo;{sentence}&rdquo;
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Info note */}
                {result.isAutoGenerated && (
                  <div className="flex items-start gap-2.5 rounded-xl border border-amber-500/20 bg-amber-500/5 p-3.5">
                    <Bot className="h-4 w-4 text-amber-400 flex-shrink-0 mt-0.5" />
                    <p className="text-xs text-amber-300/80 leading-relaxed">
                      This transcript was <strong className="text-amber-300">auto-generated by YouTube</strong>. It may contain errors, missing punctuation, or misheard words. Manual captions (when available) are more accurate.
                    </p>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
