/**
 * YouTube Transcript Extractor
 *
 * Strategy:
 * 1. Fetch the YouTube watch page via AllOrigins proxy
 * 2. Parse ytInitialPlayerResponse from the HTML to find caption track URLs
 * 3. Fetch the XML caption file (also via proxy to bypass CORS)
 * 4. Parse XML into timed transcript lines
 * 5. Generate a smart summary from the transcript text
 */

export interface TranscriptLine {
  start: number;    // seconds
  duration: number; // seconds
  text: string;
}

export interface TranscriptResult {
  lines: TranscriptLine[];
  fullText: string;
  language: string;
  isAutoGenerated: boolean;
  summary: BulletSummary;
}

export interface BulletSummary {
  title: string;
  channel: string;
  wordCount: number;
  duration: string;
  keyPoints: string[];
  topicSentences: string[];
}

const PROXY = "https://api.allorigins.win/get?url=";

/** Decode HTML entities (&amp; &#39; etc.) from XML text */
function decodeHtml(html: string): string {
  return html
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/<[^>]*>/g, "") // strip any remaining tags
    .trim();
}

/** Format seconds into MM:SS */
export function formatTime(secs: number): string {
  const m = Math.floor(secs / 60);
  const s = Math.floor(secs % 60);
  return `${m}:${s.toString().padStart(2, "0")}`;
}

/** Fetch a URL via the allorigins proxy, return raw text */
async function proxyFetch(url: string): Promise<string> {
  const res = await fetch(`${PROXY}${encodeURIComponent(url)}`);
  if (!res.ok) throw new Error(`Proxy fetch failed (${res.status})`);
  const json = await res.json();
  if (!json.contents) throw new Error("Proxy returned empty content.");
  return json.contents;
}

/**
 * Extract the ytInitialPlayerResponse JSON blob from the page HTML.
 * YouTube embeds this as a JS variable assignment in a <script> tag.
 */
function extractPlayerResponse(html: string): any {
  // Try the most common pattern first
  const patterns = [
    /ytInitialPlayerResponse\s*=\s*(\{.+?\});\s*(?:var|const|let|window|<\/script>)/s,
    /ytInitialPlayerResponse\s*=\s*(\{.+?\});/s,
  ];

  for (const pattern of patterns) {
    const match = html.match(pattern);
    if (match && match[1]) {
      try {
        return JSON.parse(match[1]);
      } catch (e) {
        // Try to find the end of the JSON object more robustly
        const start = html.indexOf("ytInitialPlayerResponse");
        if (start === -1) continue;
        const eqPos = html.indexOf("=", start);
        if (eqPos === -1) continue;
        const jsonStart = html.indexOf("{", eqPos);
        if (jsonStart === -1) continue;

        let depth = 0;
        let i = jsonStart;
        for (; i < html.length; i++) {
          if (html[i] === "{") depth++;
          else if (html[i] === "}") {
            depth--;
            if (depth === 0) break;
          }
        }
        try {
          return JSON.parse(html.slice(jsonStart, i + 1));
        } catch {
          continue;
        }
      }
    }
  }
  throw new Error("Could not find ytInitialPlayerResponse in page.");
}

/**
 * Extract caption track list from playerResponse
 */
interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind: string; // "asr" = auto-generated
  name?: string;
}

function extractCaptionTracks(playerResponse: any): CaptionTrack[] {
  const tracks: CaptionTrack[] =
    playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  return tracks;
}

/**
 * Parse the XML caption file into transcript lines
 */
function parseCaptionXml(xml: string): TranscriptLine[] {
  const parser = new DOMParser();
  const doc = parser.parseFromString(xml, "text/xml");
  const textNodes = Array.from(doc.getElementsByTagName("text"));

  if (textNodes.length === 0) {
    // Try transcript tag (older format)
    const transcriptNodes = Array.from(doc.getElementsByTagName("transcript"));
    if (transcriptNodes.length === 0) {
      throw new Error("No caption text elements found in XML.");
    }
  }

  return textNodes
    .map((node) => {
      const start = parseFloat(node.getAttribute("start") || "0");
      const dur = parseFloat(node.getAttribute("dur") || "0");
      const text = decodeHtml(node.textContent || "");
      return { start, duration: dur, text };
    })
    .filter((line) => line.text.length > 0);
}

/**
 * Extract title and channel from playerResponse
 */
function extractMeta(playerResponse: any): { title: string; channel: string } {
  const title =
    playerResponse?.videoDetails?.title ||
    playerResponse?.microformat?.playerMicroformatRenderer?.title?.simpleText ||
    "Unknown Title";
  const channel =
    playerResponse?.videoDetails?.author ||
    playerResponse?.microformat?.playerMicroformatRenderer?.ownerChannelName ||
    "Unknown Channel";
  return { title, channel };
}

/**
 * Build a smart bullet summary from transcript lines
 */
function buildSummary(
  lines: TranscriptLine[],
  title: string,
  channel: string
): BulletSummary {
  const fullText = lines.map((l) => l.text).join(" ");
  const words = fullText.split(/\s+/).filter(Boolean);
  const totalSecs = lines.length > 0 ? lines[lines.length - 1].start + lines[lines.length - 1].duration : 0;

  // Extract meaningful sentences (≥ 6 words, no music/sound tags)
  const cleaned = lines
    .map((l) => l.text)
    .filter((t) => !/^\[.*\]$/.test(t) && !/^\(.*\)$/.test(t) && t.split(" ").length >= 4)
    .map((t) => t.replace(/\[.*?\]/g, "").replace(/\(.*?\)/g, "").trim())
    .filter((t) => t.length > 10);

  // Pick every Nth line to spread across the video
  const keyPoints: string[] = [];
  const step = Math.max(1, Math.floor(cleaned.length / 5));
  for (let i = 0; i < cleaned.length && keyPoints.length < 5; i += step) {
    const pt = cleaned[i].charAt(0).toUpperCase() + cleaned[i].slice(1);
    if (!keyPoints.includes(pt)) keyPoints.push(pt);
  }

  // First and last meaningful sentences as topic sentences
  const topicSentences: string[] = [];
  if (cleaned.length > 0) {
    topicSentences.push(cleaned[0].charAt(0).toUpperCase() + cleaned[0].slice(1));
    if (cleaned.length > 1) {
      const last = cleaned[cleaned.length - 1];
      topicSentences.push(last.charAt(0).toUpperCase() + last.slice(1));
    }
  }

  return {
    title,
    channel,
    wordCount: words.length,
    duration: formatTime(totalSecs),
    keyPoints: keyPoints.length > 0 ? keyPoints : ["No key points could be extracted."],
    topicSentences,
  };
}

/**
 * Main export: fetch and parse the transcript for a YouTube video ID.
 * Prefers English captions; falls back to first available track.
 */
export async function fetchTranscript(videoId: string): Promise<TranscriptResult> {
  // Step 1: Fetch the YouTube watch page via proxy
  const pageHtml = await proxyFetch(`https://www.youtube.com/watch?v=${videoId}`);

  // Step 2: Extract playerResponse
  let playerResponse: any;
  try {
    playerResponse = extractPlayerResponse(pageHtml);
  } catch (e) {
    throw new Error(
      "Could not parse video data from YouTube. The video may be private, age-restricted, or unavailable."
    );
  }

  // Step 3: Get caption tracks
  const tracks = extractCaptionTracks(playerResponse);

  if (!tracks || tracks.length === 0) {
    throw new Error(
      "No captions available for this video. The creator may not have added subtitles, or they may be disabled."
    );
  }

  // Pick best track: prefer manual English > auto English > any English > first available
  const manualEn = tracks.find((t) => t.languageCode === "en" && t.kind !== "asr");
  const autoEn = tracks.find((t) => t.languageCode === "en" && t.kind === "asr");
  const anyEn = tracks.find((t) => t.languageCode === "en");
  const chosen = manualEn || autoEn || anyEn || tracks[0];

  const isAutoGenerated = chosen.kind === "asr";
  const language = chosen.languageCode || "unknown";

  // Step 4: Fetch the caption XML (via proxy to bypass CORS)
  let captionXml: string;
  try {
    captionXml = await proxyFetch(chosen.baseUrl);
  } catch {
    // baseUrl may need cleaning
    const cleanUrl = chosen.baseUrl.replace(/&fmt=\w+$/, "");
    captionXml = await proxyFetch(cleanUrl);
  }

  // Step 5: Parse XML
  const lines = parseCaptionXml(captionXml);

  if (lines.length === 0) {
    throw new Error("Caption file was found but contained no readable text.");
  }

  const fullText = lines.map((l) => l.text).join(" ");
  const meta = extractMeta(playerResponse);
  const summary = buildSummary(lines, meta.title, meta.channel);

  return {
    lines,
    fullText,
    language,
    isAutoGenerated,
    summary,
  };
}
